version: "3"

services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      - OPENAI_TOKEN=$OPENAI_TOKEN
      - OPENAI_PROXY=$OPENAI_PROXY
      - CHATS_WHITELIST=$CHATS_WHITELIST
      - REDIS=redis:6379
      - NEW_POSTS_CHAT_ID=-1001989824148
      - NEW_POSTS_THREAD_IDS=46567
      - NEW_POSTS_FEED_URL=https://pipmy.ru/rss/feed/posts
  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
