version: "3"

services:
  app:
    build: .
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      - OPENAI_TOKEN=$OPENAI_TOKEN
      - OPENAI_PROXY=$OPENAI_PROXY
      - CHATS_WHITELIST=$CHATS_WHITELIST
