name: cicd
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DOCKER_SSH_HOST }}
          username: deployer
          port: ${{ secrets.DOCKER_SSH_PORT }}
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          source: "*"
          target: "/home/deployer/pipmy_bot"
      - uses: appleboy/ssh-action@v1.0.0
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
          OPENAI_PROXY: ${{ secrets.OPENAI_PROXY }}
          CHATS_WHITELIST: ${{ secrets.CHATS_WHITELIST }}
          NOVOFON_KEY: ${{ secrets.NOVOFON_KEY }}
          NOVOFON_SECRET: ${{ secrets.NOVOFON_SECRET }}
          TELEGRAM_APP_ID: ${{ TELEGRAM_APP_ID }}
          TELEGRAM_APP_HASH: ${{ TELEGRAM_APP_HASH }}
        with:
          host: ${{ secrets.DOCKER_SSH_HOST }}
          port: ${{ secrets.DOCKER_SSH_PORT }}
          username: deployer
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          envs: TELEGRAM_TOKEN,OPENAI_TOKEN,OPENAI_PROXY,CHATS_WHITELIST
          script: |
            cd /home/deployer/pipmy_bot
            docker-compose up -d --build
